kind: pipeline
type: docker
name: clone

steps:
  - name: build
    image: node
    commands:
      - npm install
      - npm run build

  - name: deploy
    image: plugins/s3
    settings:
      bucket: drone-react-pipeline
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      source: /build/**/*
      target: /

  # - name: slack
  #   image: plugins/slack
  #   settings:
  #     webhook: https://hooks.slack.com/services/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
  #     channel: random
  #     template: >
  #       {{#success build.status}}
  #         build {{build.number}} succeeded. Good job.
  #       {{else}}
  #         build {{build.number}} failed. Fix me please.
  #       {{/success}}

trigger: # 觸發 pipeline 條件，分支為 master，且進行 push 行為
  branch:
    - master
  event:
    - push
