kind: pipeline
type: docker
name: clone

steps:
  - name: dronetest
    image: node
    commands:
      - npm install
      - npm run build

  - name: deploy
    image: plugins/s3
    settings:
      bucket: drone-react-pipeline
      access_key: AKIAIP36U7IFFQHF7W7Q
      secret_key: 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
      source: public/**/*
      target: /target/location

  # - name: slack
  #   image: plugins/slack
  #   settings:
  #     webhook: https://hooks.slack.com/services/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
  #     channel: random
  #     template: >
  #       {{#success build.status}}
  #         build {{build.number}} succeeded. Good job.
  #       {{else}}
  #         build {{build.number}} failed. Fix me please.
  #       {{/success}}

trigger: # 觸發 pipeline 條件，分支為 master，且進行 push 行為
  branch:
    - master
  event:
    - push
